spring.application.name=ds

spring.output.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.200.4.221:3306/bryan_severo_ds?createDatabaseIfNotExist=true
spring.datasource.username=bryan_severo
spring.datasource.password= 467557

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true